# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 738)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 891, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_loading = QtWidgets.QWidget()
        self.tab_loading.setObjectName("tab_loading")
        self.pushButton_loading = QtWidgets.QPushButton(self.tab_loading)
        self.pushButton_loading.setGeometry(QtCore.QRect(570, 170, 191, 81))
        self.pushButton_loading.setObjectName("pushButton_loading")
        self.textEdit_output = QtWidgets.QTextEdit(self.tab_loading)
        self.textEdit_output.setGeometry(QtCore.QRect(80, 260, 741, 391))
        self.textEdit_output.setObjectName("textEdit_output")
        self.progressBar = QtWidgets.QProgressBar(self.tab_loading)
        self.progressBar.setGeometry(QtCore.QRect(100, 90, 721, 21))
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setProperty("value", 10)
        self.progressBar.setObjectName("progressBar")
        self.tableWidget_load = QtWidgets.QTableWidget(self.tab_loading)
        self.tableWidget_load.setGeometry(QtCore.QRect(210, 170, 311, 81))
        self.tableWidget_load.setRowCount(2)
        self.tableWidget_load.setColumnCount(3)
        self.tableWidget_load.setObjectName("tableWidget_load")
        self.label_3 = QtWidgets.QLabel(self.tab_loading)
        self.label_3.setGeometry(QtCore.QRect(290, 10, 251, 21))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.tab_loading)
        self.label_6.setGeometry(QtCore.QRect(300, 140, 131, 20))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.tab_loading)
        self.label_4.setGeometry(QtCore.QRect(150, 40, 571, 30))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_loading, "")
        self.tab_eda = QtWidgets.QWidget()
        self.tab_eda.setObjectName("tab_eda")
        self.pushButton_EDA = QtWidgets.QPushButton(self.tab_eda)
        self.pushButton_EDA.setGeometry(QtCore.QRect(10, 70, 201, 41))
        self.pushButton_EDA.setObjectName("pushButton_EDA")
        self.MplWidget = MplWidget(self.tab_eda)
        self.MplWidget.setGeometry(QtCore.QRect(0, 140, 901, 501))
        self.MplWidget.setMinimumSize(QtCore.QSize(400, 300))
        self.MplWidget.setObjectName("MplWidget")
        self.comboBox_eda = QtWidgets.QComboBox(self.tab_eda)
        self.comboBox_eda.setGeometry(QtCore.QRect(20, 20, 161, 32))
        self.comboBox_eda.setObjectName("comboBox_eda")
        self.comboBox_eda.addItem("")
        self.comboBox_eda.addItem("")
        self.comboBox_eda.addItem("")
        self.comboBox_eda.addItem("")
        self.pushButton_EDA_sev = QtWidgets.QPushButton(self.tab_eda)
        self.pushButton_EDA_sev.setGeometry(QtCore.QRect(400, 30, 201, 41))
        self.pushButton_EDA_sev.setObjectName("pushButton_EDA_sev")
        self.pushButton_EDA_temp = QtWidgets.QPushButton(self.tab_eda)
        self.pushButton_EDA_temp.setGeometry(QtCore.QRect(620, 80, 201, 41))
        self.pushButton_EDA_temp.setObjectName("pushButton_EDA_temp")
        self.pushButton_EDA_hum = QtWidgets.QPushButton(self.tab_eda)
        self.pushButton_EDA_hum.setGeometry(QtCore.QRect(400, 80, 201, 41))
        self.pushButton_EDA_hum.setObjectName("pushButton_EDA_hum")
        self.pushButton_EDA_pre = QtWidgets.QPushButton(self.tab_eda)
        self.pushButton_EDA_pre.setGeometry(QtCore.QRect(620, 30, 201, 41))
        self.pushButton_EDA_pre.setObjectName("pushButton_EDA_pre")
        self.pushButton_EDA_sun = QtWidgets.QPushButton(self.tab_eda)
        self.pushButton_EDA_sun.setGeometry(QtCore.QRect(200, 30, 201, 41))
        self.pushButton_EDA_sun.setObjectName("pushButton_EDA_sun")
        self.tabWidget.addTab(self.tab_eda, "")
        self.tab_features = QtWidgets.QWidget()
        self.tab_features.setObjectName("tab_features")
        self.MplWidget_2 = MplWidget(self.tab_features)
        self.MplWidget_2.setGeometry(QtCore.QRect(20, 10, 831, 601))
        self.MplWidget_2.setMinimumSize(QtCore.QSize(611, 300))
        self.MplWidget_2.setObjectName("MplWidget_2")
        self.pushButton_feature = QtWidgets.QPushButton(self.tab_features)
        self.pushButton_feature.setGeometry(QtCore.QRect(340, 620, 191, 41))
        self.pushButton_feature.setObjectName("pushButton_feature")
        self.tabWidget.addTab(self.tab_features, "")
        self.tab_modeling = QtWidgets.QWidget()
        self.tab_modeling.setObjectName("tab_modeling")
        self.pushButton_rf_bagging = QtWidgets.QPushButton(self.tab_modeling)
        self.pushButton_rf_bagging.setGeometry(QtCore.QRect(360, 540, 161, 41))
        self.pushButton_rf_bagging.setObjectName("pushButton_rf_bagging")
        self.label_7 = QtWidgets.QLabel(self.tab_modeling)
        self.label_7.setGeometry(QtCore.QRect(170, 20, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.MplWidget_3 = MplWidget(self.tab_modeling)
        self.MplWidget_3.setGeometry(QtCore.QRect(450, 50, 440, 441))
        self.MplWidget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.MplWidget_3.setObjectName("MplWidget_3")
        self.textEdit_classification_report = QtWidgets.QTextEdit(self.tab_modeling)
        self.textEdit_classification_report.setGeometry(QtCore.QRect(10, 60, 431, 421))
        self.textEdit_classification_report.setObjectName("textEdit_classification_report")
        self.label_11 = QtWidgets.QLabel(self.tab_modeling)
        self.label_11.setGeometry(QtCore.QRect(550, 20, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_modeling, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(170, 20, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textEdit_classification_report_ad = QtWidgets.QTextEdit(self.tab)
        self.textEdit_classification_report_ad.setGeometry(QtCore.QRect(10, 60, 431, 421))
        self.textEdit_classification_report_ad.setObjectName("textEdit_classification_report_ad")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(550, 20, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.MplWidget_4 = MplWidget(self.tab)
        self.MplWidget_4.setGeometry(QtCore.QRect(450, 50, 440, 441))
        self.MplWidget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.MplWidget_4.setObjectName("MplWidget_4")
        self.pushButton_ad = QtWidgets.QPushButton(self.tab)
        self.pushButton_ad.setGeometry(QtCore.QRect(360, 540, 161, 41))
        self.pushButton_ad.setObjectName("pushButton_ad")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Traffic Accident in USA  Predictor"))
        self.pushButton_loading.setText(_translate("MainWindow", "Load Data"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#084fd1;\">Data Mining Project - Group 5</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "High Level Summary "))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#29c832;\">Exploring Factors that Impact  Car Accident Severity</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_loading), _translate("MainWindow", "Loading"))
        self.pushButton_EDA.setText(_translate("MainWindow", "Plot"))
        self.comboBox_eda.setItemText(0, _translate("MainWindow", "Select"))
        self.comboBox_eda.setItemText(1, _translate("MainWindow", "Severity"))
        self.comboBox_eda.setItemText(2, _translate("MainWindow", "Temperature"))
        self.comboBox_eda.setItemText(3, _translate("MainWindow", "Humidity"))
        self.pushButton_EDA_sev.setText(_translate("MainWindow", "Severity"))
        self.pushButton_EDA_temp.setText(_translate("MainWindow", "Temperature"))
        self.pushButton_EDA_hum.setText(_translate("MainWindow", "Humidity"))
        self.pushButton_EDA_pre.setText(_translate("MainWindow", "Pressure"))
        self.pushButton_EDA_sun.setText(_translate("MainWindow", "Sunrise Sunset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_eda), _translate("MainWindow", "EDA"))
        self.pushButton_feature.setText(_translate("MainWindow", "Run Random Forest"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_features), _translate("MainWindow", "Feature Selection"))
        self.pushButton_rf_bagging.setText(_translate("MainWindow", "Run Model"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0a5fff;\">Classification Report</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0a5fff;\">Confustion Matrix</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_modeling), _translate("MainWindow", "RF - Bagging"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0a5fff;\">Classification Report</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0a5fff;\">Confustion Matrix</span></p></body></html>"))
        self.pushButton_ad.setText(_translate("MainWindow", "Run Model"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Adaptive Boosting Trees"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

